<?php

namespace AppBundle\Repository;

/**
 * NearearthobjectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NearearthobjectsRepository extends \Doctrine\ORM\EntityRepository
{
}
